version: "3.8"
services:
  app:
    build: .
    container_name: book-store-app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/bookstoreapp
      - JWT_SECRET=your_jwt_secret_here
      - NODE_ENV=development
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  db:
    image: postgres:13-alpine
    container_name: postgres-book-store-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookstoreapp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 3s

volumes:
  postgres-data:
